spring:

 datasource:
  url: jdbc:postgresql://localhost:5432/hello_plant
  username: postgres
  password: postgres
  driver-class-name: org.postgresql.Driver
 
 flyway:
  baselineOnMigrate: true
  locations: classpath:db/migration
  schemas: public
  enabled: true

# jpa:
#   hibernate:
#     ddl-auto: update